### ISSUE TITLE
bvar is busy at sampling for 2 seconds

### ISSUE THREAD

**Issue by hustnn** [apache/incubator-brpc#1383]
We found this issue once but it is hard to reproduce.

Anyone has some idea on the possible reason to trigger it?  How serious it is?

Thanks.

**Comment by hotaery** [comment]
https://github.com/apache/incubator-brpc/blob/master/src/bvar/detail/sampler.cpp#L189
here is code. brpc has sampling thread. if your project register too many bvar, this thread will consume more time than threshold so that print this log. 
```cpp
bvar::Adder adder("example");
```
maybe your project use bvar like this. Normally, it not affect performance. But i suggest don't use too many named bvar :)

**Comment by serverglen** [comment]
Usually it's because the machine is overloaded, closed
