### ISSUE TITLE
Cannot build example programs when following the build instruction on Arch Linux

### ISSUE THREAD

**Issue by VOID001** [apache/incubator-brpc#1498]
**Describe the bug (描述bug)**
The example programs including `echo_server` and `echo_client` cannot run and complains about a linking problem:
```
ERROR: something wrong with flag 'flagfile' in file '/build/gflags/src/gflags-2.2.2/src/gflags.cc'.  One possibility: file '/build/gflags/src/gflags-2.2.2/src/gflags.cc' is being linked both statically and dynamically into this executable.
```

**To Reproduce (复现方法)**

0. Verify that libgflags.a is in the library search path
1. `./config_brpc.sh --headers=/usr/include --libs=/usr/lib --with-glog; make -j8`
2. `make -C example/echo_c++/; example/echo_c++/echo_server`

**Expected behavior (期望行为)**
Server should start

**Versions (各种版本)**
OS: `Arch Linux Linux  5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linux`
Compiler: `g++ (GCC) 11.1.0`
brpc: d37a553fa8f5bd0a491a854048c9302ee42c00f4
protobuf:
gflags: 2.2.2

**Additional context/screenshots (更多上下文/截图)**

I think the problem is caused by "both static libgflags.a and dynamic libgflags.so" are linked in the example program. Following is my config.mk (generated from config_brpc.sh)

```
# Generated by config_brpc.sh, don't modify manually
SYSTEM=Linux
HDRS=/usr/include/
LIBS=/usr/lib
PROTOC=/usr/bin/protoc
PROTOBUF_HDR=/usr/include/
CC=gcc
CXX=g++
GCC_VERSION=110100
STATIC_LINKINGS= -lgflags
DYNAMIC_LINKINGS=-lpthread -lrt -lssl -lcrypto -ldl -lz -lprotobuf -lleveldb
CPPFLAGS=-DBRPC_WITH_GLOG=1 -DGFLAGS_NS=google -g
ifeq ($(NEED_LIBPROTOC), 1)
    DYNAMIC_LINKINGS+=-lprotoc
endif
ifeq ($(NEED_GPERFTOOLS), 1)
    DYNAMIC_LINKINGS+=-ltcmalloc_and_profiler
endif
DYNAMIC_LINKINGS+=-lglog
ifeq ($(NEED_GTEST), 1)
    DYNAMIC_LINKINGS+=-lgtest
    DYNAMIC_LINKINGS+=-lgtest_main
endif
```
First, the libbrpc.so build instruction, all libraries (STATIC + DYNAMIC LINKINGS) are linked dynamically. 
Then, in the config.mk file, libgflags is detected as a static library, however the when building the examples, they are trying to link `libbrpc.so` as well as `libgflags.a`, results in a incorrect linking setting.

There are two solutions to workaround
1. Pass  `LINK_SO=0` environment variable when building examples
2. dynamic link `DYNAMIC_LINKINGS` and `STATIC_LINKINGS` (such as gflags in this case) when building examples.

**Comment by VOID001** [comment]
I tried the same instructions on a Ubuntu container, it works without any problem.

**Comment by VOID001** [comment]
This is reproducible on a clean archlinux container.
Script to reproduce in a clean container

```sh
set -e

pacman -Sy
pacman -S --noconfirm google-glog git gcc protobuf glibc leveldb make libxcrypt which 
# git clone https://github.com/apache/incubator-brpc # clone if needed
cd incubator-brpc
# git checkout d37a553fa8f5bd0a491a854048c9302ee42c00f4 # checkout if needed
./config_brpc.sh --headers=/usr/include --libs=/usr/lib --with-glog; make -j8
make -C example/echo_c++/
./example/echo_c++/echo_server

```

The script will exit will failure and the same error log showed above
```
ERROR: something wrong with flag 'flagfile' in file '/build/gflags/src/gflags-2.2.2/src/gflags.cc'.  One possibility: file '/build/gflags/src/gflags-2.2.2/src/gflags.cc' is being linked both statically and dynamically into this executable.
```

**Comment by TousakaRin** [comment]
I reproduced this problem through the image you provided，

The root cause of the problem is like this：
1.  you enabled --with-glog when you run config_brpc.sh, so glog will be linked, and the script only found a dynamic library(libglog.so), so glog will be dynamic linked. Similarly, gflag will be linked in a static way
2. gflag is referenced by glog,  and libglog.so linked gflags in dynamic way, it is reasonable.
3. in some platform, gflags.a is packed without option '-fPIC', and it is the default behavior when compiling gflag, so when you link ./example/echo_c++/echo_server with **libgflags.a and libglog.so**,  error occured.

in some other platform , even if they are packaging static libraries, they will add options '-fPIC', for example Ubuntu. to solve this promble, compile gflags with source code, and set CPPFLAGS=-fPIC, then everything works fine.

**Comment by TousakaRin** [comment]
I reproduced this problem through the image you provided，
   
   The root cause of the problem is like this：
   1.  you enabled --with-glog when you run config_brpc.sh, so glog will be linked, and the script only found a dynamic library(libglog.so), so glog will be dynamic linked. Similarly, gflag will be linked in a static way
   2. gflag is referenced by glog,  and libglog.so linked gflags in dynamic way, it is reasonable.
   3. in some platform, gflags.a is complied without option '-fPIC', and it is the default behavior when compiling gflag, so when you link ./example/echo_c++/echo_server with **libgflags.a and libglog.so**,  error occured.
   
   In some other platform , even if they are compiling static libraries, they will add options '-fPIC', for example Ubuntu. to solve this promble, compile gflags with source code, and set **CPPFLAGS=-fPIC**, then everything works fine.
