### ISSUE TITLE
A question about supporting TCP keepalive

### ISSUE THREAD

**Issue by lingbin** [apache/incubator-brpc#731]
In the current implementation, the parameter that sets the `TCP keepalive` is not found. 

The problem is that if the client is abnormally down (such as restarting after power failure), the server may have a large number of semi-connected states, that is, The client side can't see these connections (`netstat -apno`), but it still maintains a large number of `ESTABLISHED` status links on the server side.
At the same time, since linux does not open keepalive by default, if these connections have no data transmission, then it will always exist, and it will consume the resources of the server. And if the server side has some resource restrictions (such as limiting the total number of fd), the system will face the problem of service failure.

Therefore, I feel that Brpc as an rpc library should be able to allow `TCP keepalive` to be manually enabled in the program.

If there is no other special consideration in the Brpc, I can submit a PR

**Comment by zyearn** [comment]
Currently if client is abnormally down, and ServerOptions.idle_timeout_sec in server side is set properly, then the connection should be closed after idle_timeout_sec as expected.
But problem happens when server is abnormally down, client would never know this situation if the connection type is single or short with no timeout until next rpc is sent to broken servers. If the connection type is short with timeout, connection would be closed after timeout is reached. The last case is pooled connection, which may not be the problem since it is controlled by FLAGS_idle_timeout_second.

**Comment by lingbin** [comment]
Thank you for your reply which let me know more.
It seems that it  is still beneficial if we can enable TCP keepalive manually, please also review my  PR #733 , thanks

**Comment by lingbin** [comment]
In addition to this page, there are also some comments in #733 . 
The conclusion of this issue is clear, So now close the issue.
