### ISSUE TITLE
请教BRPC 如果请求是多线程写一个地方，需要加锁么

### ISSUE THREAD

**Issue by alicialin** [apache/incubator-brpc#755]
**Describe the bug (描述bug)*
因为BRPC 内部是系统级开的线程，对用户无感，如果请求是多线程写同一个地方，是否需要加锁，加锁后，整体性能是不是变慢？
BRPC 用户能知道开了多少线程么？比如一上来

**Comment by zyearn** [comment]
please read https://github.com/apache/incubator-brpc/blob/master/docs/en/client.md and https://github.com/apache/incubator-brpc/blob/master/docs/en/server.md for more details. After reading some basic materials and you still have questions, make you questions clear and concise so that I can know how to help, thanks

**Comment by alicialin** [comment]
感谢回复，可能我的问题没有问得比较明白。其实再BRPC 同步模型下服务使用的是bthead, 一般多线程写一个一个内存单元（比如数组）需要加锁。但是可能通过设计思路把，一个数组拆分成32个数组，那么同时写，就可以规避加锁问题。我的意思是，比如你知道服务器开了多少个线程，通过HASH 的方式，分开写，让1个线程写一个地方，这样并发度就可以达到32，但是在咋们这种情况下。bthead不等同于pthead, 我的意思是不是不能等用同样的方式，来达到不加锁的方式。

**Comment by jamesge** [comment]
即使消除了线程间的写-写冲突，也无法消除了读-写冲突。你先了解一下并发相关的知识，再回头思考一下这个问题吧。
