### ISSUE TITLE
When the deadline start to make effect? 

### ISSUE THREAD

**Issue by hittingnote** [apache/incubator-brpc#790]
Recently, I really care about when the deadline start to count down. I know that if server doesn't return results before deadline, i.e., t_res is greater than D, the request is invalid, but I don't know whether t_res includes the duration that the args are marshaled and the request is waiting for being sent at the client. Does the deadline start to count down after the request is sent out?

I know that in grpc, the time taken for buffering in HTTP/2, TCP and the network is all part of deadline count down, but I think what deadline includes might be different in other RPC framworks. So I hope anyone can tell me when deadline starts to count down in brpc. Thanks!

**Comment by jamesge** [comment]
The deadline timer in brpc starts when the user calls Channel::CallMethod() which includes request marshaling, buffering, sending (nearly all steps of a RPC). If the packet containing the response(which may not be parsed yet) comes back before the deadline, the timer is removed. Otherwise the RPC ends with ERPCTIMEDOUT error.
